### ISSUE TITLE
Crashes in Safari

### ISSUE THREAD

**Issue by Haroenv** [tbfleming/cib#1]
On both iOS (11) and desktop Safari (latest tech preview) pressing "Compile" makes the browser reload "because a problem occurred", I'm not exactly sure how to debug this, since the devtools also disappear. 

<img width="395" alt="screen shot 2018-01-02 at 13 37 07" src="https://user-images.githubusercontent.com/6270048/34483981-27f685b6-efc2-11e7-8874-60ca4158e487.png">

**Comment by tbfleming** [comment]
I have a long history of banging my head on my desk when dealing with Safari (e.g. https://github.com/tbfleming/jscut/issues/24). Maybe someone can help diagnose it?

To be fair, Chrome 64 Beta also gives up the ghost on it even though Chrome 63 works.

**Comment by arasouli91** [comment]
I want to fix this, unfortunately I don't have consistent access to a Mac. Here is what the console says on Safari:

[Log] clang-format – "Can't put compiled module in object store" (process.js, line 140)
[Log] runtime – "Can't put compiled module in object store" (process.js, line 140)
[Log] clang – "Can't put compiled module in object store" (process.js, line 140)
[Error] Failed to load resource: the server responded with a status of 404 () (goldenlayout-light-theme.css.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (editor.main.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (loader.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (workerMain.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 () (goldenlayout-base.css.map, line 0)

I'll try to get back on a Mac sometime and see what I can do.

**Comment by tbfleming** [comment]
None of those are fatal. The first 3 mean Safari doesn't allow scripts to manually cache compiled binaries; Chrome doesn't either. The 404s are for source maps I didn't include; only useful for debugging Golden Layout and Monaco.

**Comment by kkebo** [comment]
The issues seems to be resolved in Safari Technology Preview Release 60. No errors happen during initialing, compiling, and running.

**Comment by Haroenv** [comment]
Yep, seems to work without issue now (except being really slow but I guess that's normal). I'm using release 59 of tech preview:

<img width="1440" alt="screen shot 2018-07-10 at 16 00 42" src="https://user-images.githubusercontent.com/6270048/42514778-7cc0ba8a-845a-11e8-9b48-441a586b222c.png">
