### ISSUE TITLE
Can you please provide the binaries?

### ISSUE THREAD

**Issue by christosnc** [tbfleming/cib#16]
Hello,

I tried to build the project twice, without any success.
I have an EC2 Ubuntu machine, clean, with the packages you said to install. (nodejs instead of nodejs-legacy and libboost-all-tools instead of libboost1.58-tools-dev)
The repos are downloaded, cmake starts, then ninja starts, but at the very end, the whole thing stops with some error.

**Building this takes a lot of time.** (And apparently I may get an error after 5 hours of building)
Can you please provide the pre-built binaries for easier testing?

Thank you!

**Comment by tbfleming** [comment]
Prebuilt binaries are in the gh-pages branch

**Comment by christosnc** [comment]
Thank you, I would never find it!
