### ISSUE TITLE
Libclang in WASM

### ISSUE THREAD

**Issue by mannprerak2** [tbfleming/cib#22]
I wanted to ask if it would be possible to compile Libclang (C interface to clang) to WASM?

I am a complete noob here, please feel free to close this issue if this question is totally ridiculous. 🙈

**Comment by tbfleming** [comment]
That is possible, but will take work. cib is now pretty far behind on llvm updates. https://binji.github.io/wasm-clang/ is newer.

**Comment by tbfleming** [comment]
GH link: https://github.com/binji/wasm-clang

**Comment by mannprerak2** [comment]
Thanks, I'll check that out.
