### ISSUE TITLE
building when you already have emscripten installed

### ISSUE THREAD

**Issue by zwhitchcox** [tbfleming/cib#4]
Do you have any instructions for if you already have emscripten installed? I tried deleting `~/.emscripten`, but it still didn't work.

**Comment by tbfleming** [comment]
Try ```rm -rf ~/.emscripten*```; this will get some folders it creates. Also make sure it's not in your PATH and none of its environment variables are set.

**Comment by tbfleming** [comment]
Once a failure like that occurs the build script will get confused by already-existing but not correctly-filled subfolders and files. Try ```rm -rf build install dist ~/.emscripten*``` .

**Comment by zwhitchcox** [comment]
Awesome, it worked, thanks!
