### ISSUE TITLE
LinkError: import object field 'sqlite3_open' is not a Function

### ISSUE THREAD

**Issue by mikeptweet** [tbfleming/cib#7]
I am trying to compile and run the following example and I get this error ...

// cib:{"fetch":"https://cdn.rawgit.com/mikeptweet/HelloWorld/21a97199/sqlite.zip", "system_includes":["."], "unzip_compiler":true}
#include "sqlite/sqlite3.h"
#include <stdio.h>

int main(void) {
    
    sqlite3 *db;
    sqlite3_stmt *res;
    
    int rc = sqlite3_open(":memory:", &db);
    
    if (rc != SQLITE_OK) {
        
        fprintf(stderr, "Cannot open database: %s\n", sqlite3_errmsg(db));
        sqlite3_close(db);
        
        return 1;
    }
    
    rc = sqlite3_prepare_v2(db, "SELECT SQLITE_VERSION()", -1, &res, 0);    
    
    if (rc != SQLITE_OK) {
        
        fprintf(stderr, "Failed to fetch data: %s\n", sqlite3_errmsg(db));
        sqlite3_close(db);
        
        return 1;
    }    
    
    rc = sqlite3_step(res);
    
    if (rc == SQLITE_ROW) {
        printf("%s\n", sqlite3_column_text(res, 0));
    }
    
    sqlite3_finalize(res);
    sqlite3_close(db);
    
    return 0;
}

**Comment by tbfleming** [comment]
sqlite requires compiling a .c file; cib only supports C++ right now.

**Comment by mikeptweet** [comment]
Ok ... thanks. 

Yet the following works :-)

#include <stdio.h>

int sum(int a, int b)
{
  return a + b;
}


int main() {
    printf("%d\n", sum(39, 3));
    return 0;
}

**Comment by tbfleming** [comment]
cib's runtime includes most of the C standard library, most of the C++ standard library, and parts of emscripten's library. Its linker/loader knows how to bring in cib's runtime, but not anything else.

**Comment by mikeptweet** [comment]
OK ... thanks.

And THANKS for this great website. It is such a great way to start playing around with webassembly :-)
